# Generated by Django 4.0 on 2023-07-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название продукта')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('weight', models.CharField(max_length=50, verbose_name='Вес товара')),
                ('price', models.IntegerField(verbose_name='Цена товара')),
                ('category', models.CharField(choices=[('pizza', 'Пицца'), ('roll', 'Ролл'), ('burger', 'Бургер')], max_length=50, verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
