# Generated by Django 4.0 on 2023-07-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=23, upload_to='products/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
