# Generated by Django 4.0 on 2023-07-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='only_pizza_size',
            field=models.CharField(blank=True, choices=[('30 cm', '30 см'), ('35 cm', '35 см'), ('40 cm', '40 см')], default='', max_length=10, verbose_name='Размер пиццы'),
        ),
    ]
