# Generated by Django 4.0 on 2023-07-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_only_pizza_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=12, max_length=100, verbose_name='url товара'),
            preserve_default=False,
        ),
    ]
