# Generated by Django 4.0 on 2023-07-25 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_customuser'),
        ('products', '0007_alter_product_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=25, verbose_name='Имя получателя')),
                ('client_phone_number', models.CharField(max_length=25, verbose_name='Номер телефона получателя')),
                ('client_address', models.CharField(max_length=100, verbose_name='Адрес получателя')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.member', verbose_name='Пользователь сделавший заказ')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_total_price', models.IntegerField(verbose_name='Общая цена товара одной позиции в заказе')),
                ('product_total_count', models.IntegerField(verbose_name='Общее количество товара одной позиции в заказе')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.order', verbose_name='Номер заказа')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product', verbose_name='Номер товара')),
            ],
        ),
    ]
