# Generated by Django 4.0 on 2023-07-25 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_order_order_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_total_price',
            new_name='total_price',
        ),
    ]
