# Generated by Django 4.0 on 2023-07-29 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_order_bonuses_was_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bonuses_was_used',
        ),
    ]
