# Generated by Django 4.0 on 2023-07-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_order_bonuses_was_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bonuses_was_used',
            field=models.IntegerField(default=23, verbose_name='Сколько использовано бонусов'),
            preserve_default=False,
        ),
    ]
