# Generated by Django 4.0 on 2023-07-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_order_bonuses_was_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bonuses_was_used',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сколько использовано бонусов'),
        ),
    ]
