# Generated by Django 4.0 on 2023-07-29 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_client_address'),
        ('products', '0015_alter_order_bonuses_was_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.client_address', verbose_name='Адрес пользователя'),
        ),
    ]
