# Generated by Django 4.0 on 2023-07-30 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_address_remove_client_address_client_and_more'),
        ('products', '0016_alter_order_client_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.address', verbose_name='Адрес пользователя'),
        ),
    ]
