# Generated by Django 4.0 on 2023-08-23 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_address_profile_alter_bonussystem_profile'),
        ('products', '0017_alter_order_client_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.AddField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='Пользователь сделавший заказ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bonuses_was_used',
            field=models.IntegerField(default=0, verbose_name='Сколько использовано бонусов'),
        ),
    ]
