version: '3.11'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    container_name: db
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  backend:
    build:
      context: ../food_shop
    container_name: backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
      - templates_volume:/app/templates/

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    depends_on: 
     - backend
  celery:
    build:
      context: ../food_shop
    command: celery -A food_shop worker --loglevel=info
    depends_on:
      - redis
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
      - templates_volume:/var/html/templates/
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  static_volume:
  media_volume:
  templates_volume: