# Generated by Django 4.0 on 2023-07-15 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_member_last_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
