# Generated by Django 4.0 on 2023-07-28 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('sex', models.CharField(choices=[('male', 'мужской'), ('female', 'женский')], default='Не указан', max_length=10, verbose_name='Пол')),
                ('date_of_birthday', models.DateField(verbose_name='Дата рождения')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('orders_price_amount', models.IntegerField(verbose_name='Общая сумма заказов')),
                ('bonuses_amount', models.IntegerField(verbose_name='Количестко бонусов')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.member', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
