# Generated by Django 4.0 on 2023-07-28 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_order_total_price_order_total_price'),
        ('users', '0008_alter_profile_address_alter_profile_bonuses_amount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Client',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='member',
            new_name='client',
        ),
    ]
