# Generated by Django 4.0 on 2023-07-29 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_member_client_rename_member_profile_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес пользователя')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client', verbose_name='Пользователь')),
            ],
        ),
    ]
