# Generated by Django 4.0 on 2023-07-30 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_order_client_address'),
        ('users', '0011_address_remove_client_address_client_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client_address',
        ),
        migrations.AddField(
            model_name='address',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client', verbose_name='Пользователь'),
        ),
    ]
