# Generated by Django 4.0 on 2023-08-15 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_client_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bonuses_amount',
        ),
        migrations.CreateModel(
            name='BonusSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonuses_amount', models.IntegerField(default=0, verbose_name='Количестко бонусов')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='Пользователь')),
            ],
        ),
    ]
