# Generated by Django 4.0 on 2023-08-15 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_profile_bonuses_amount_bonussystem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='client',
        ),
        migrations.AddField(
            model_name='address',
            name='Profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bonussystem',
            name='bonuses_amount',
            field=models.IntegerField(default=0, verbose_name='Количество бонусов'),
        ),
    ]
