# Generated by Django 4.0 on 2023-08-15 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_address_profile_alter_bonussystem_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='Profile',
            new_name='profile',
        ),
    ]
