# Generated by Django 4.0 on 2023-08-23 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_profile_address_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.profile', verbose_name='Профиль пользователя'),
        ),
        migrations.AlterField(
            model_name='bonussystem',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='users.profile', verbose_name='Пользователь'),
        ),
    ]
